# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kfilemetadata': '@stable'
    'frameworks/baloo': '@stable'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kfilemetadata': '@latest-kf6'
    'frameworks/baloo': '@latest-kf6'

Options:
    require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
